### ISSUE TITLE
Issue with Falcon App

### ISSUE THREAD

**Issue by stuckinthe** [ParrotDevelopers/FalconChannelGuide#1]
I'm not sure if this is the proper place to post. The Falcon app no longer works since the weboasis api website gives an Argo tunnel error.

**Comment by ParrotDevel0per** [comment]
Sorry for the late reply, had a lot of work, well basically hosting is down, im working on a backup, i have no idea how long it will take but i will for sure post it here

**Comment by ParrotDevel0per** [comment]
should be live again, we'll continue to fix sources
